### PR TITLE
Improve resume predictions

### PR DESCRIPTION
**Pull request by DimaMolod**
Read from pkl and update prediction results in the loop where the calculation of START is made. Don't update prediction_result with sequence and protein if already present in the dict. Read & update from pkl is moved to a separate function for clarity.

### CODE REVIEW

**Comment by dingquanyu** [comment]
Variables not defined in _read_from_prediction_result function: 
```multimeric_obejct```: https://github.com/KosinskiLab/AlphaPulldown/blob/03d5a8d4770a3c7d503c5f1ad029b6720f497e60/alphapulldown/folding_backend/alphafold_backend.py#L134
```processed_feature_dict```: https://github.com/KosinskiLab/AlphaPulldown/blob/03d5a8d4770a3c7d503c5f1ad029b6720f497e60/alphapulldown/folding_backend/alphafold_backend.py#L141
```model_runner```:  https://github.com/KosinskiLab/AlphaPulldown/blob/03d5a8d4770a3c7d503c5f1ad029b6720f497e60/alphapulldown/folding_backend/alphafold_backend.py#L144

**Review by dingquanyu — APPROVED** [review]

**Comment by dingquanyu** [comment]
@DimaMolod looks good! Just to double check, all of your result pickles were retained in this version where remove pickle is turned to False by default right?

**Comment by DimaMolod** [comment]
> @DimaMolod looks good! Just to double check, all of your result pickles were retained in this version where remove pickle is turned to False by default right?

That's right. Otherwise, it will start predicting anew from model 2 for all finished jobs(complexes)

**Comment by dingquanyu** [comment]
> > @DimaMolod looks good! Just to double check, all of your result pickles were retained in this version where remove pickle is turned to False by default right?
> 
> That's right. Otherwise, it will start predicting anew from model 2 for all finished jobs(complexes)

Great I will merge them then and close issue #352

**Pull request merged**
