### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jkosinski**
A cosmetic rearrangement in order to:
1) separate conda from pip
2) have conda step in a separate heading so we can link to it from the developer guide

### CODE REVIEW

**Comment by DimaMolod** [comment]
I suggest we move hhsuite from optional to main since we need the conversion script from a3m to fasta

**Comment by jkosinski** [comment]
> I suggest we move hhsuite from optional to main since we need the conversion script from a3m to fasta

Right, indeed. Should be fine and those people who want to use their own from their system (e.g. compiled with some optimizations) could just remove that from installation command.

**Comment by DimaMolod** [comment]
all right! then let's wait if it works for you on gpu with 

`pip install jax==0.4.20 jaxlib==0.4.16+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

and if so correct this command in README.md, move hhsuite installation from optional to mandatory, and merge it together with your corrections to main.

**Comment by jkosinski** [comment]
> all right! then let's wait if it works for you on gpu with
> 
> `pip install jax==0.4.20 jaxlib==0.4.16+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
> 
> and if so correct this command in README.md, move hhsuite installation from optional to mandatory, and merge it together with your corrections to main.

OK, as mentioned, the command works for me for dev version but you should add it to the manual only if it works for the PyPi version too.

**Comment by DimaMolod** [comment]
wait I thought you said yesterday that it worked for you when installed from pypi but you can't fix the bug about multiple feats directories so want to make dev version also work. Pypi also doesn't work?!

**Comment by jkosinski** [comment]
> wait I thought you said yesterday that it worked for you when installed from pypi but you can't fix the bug about multiple feats directories so want to make dev version also work. Pypi also doesn't work?!

Pypi works but I haven't tested with the new jax installation command.

**Comment by DimaMolod** [comment]
ok, I see. Before we merge and set in stone these jax/jaxlib versions (for some time, at least), I'd try first with the newest jax 0.4.23 (https://github.com/google/jax/releases) just to make sure there will be no problems due to different jax/jaxlib versions. 
TLTR Don't merge this PR just yet :-)

**Comment by jkosinski** [comment]
> ok, I see. Before we merge and set in stone these jax/jaxlib versions (for some time, at least), I'd try first with the newest jax 0.4.23 (https://github.com/google/jax/releases) just to make sure there will be no problems due to different jax/jaxlib versions. TLTR Don't merge this PR just yet :-)

I have now run both pypi and dev with:
`pip install jax==0.4.23 jaxlib==0.4.23+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
and both work for me :-)

**Review by DimaMolod — APPROVED** [review]

**Pull request merged**
