### PR TITLE
Remove a Protein object from result.pkl during postprocessing

### PR DESCRIPTION
**Pull request by DimaMolod**

### CODE REVIEW

**Comment by dingquanyu** [comment]
I needed to add an extra line of updating the dictionary in the post process, otherwise it crashed later on. but this will not cause the error in the analysis pipeline as the the result pickles were already written out before reaching here.

**Comment by DimaMolod** [comment]
> I needed to add an extra line of updating the dictionary in the post process, otherwise it crashed later on. but this will not cause the error in the analysis pipeline as the the result pickles were already written out before reaching here.

Good point. I've also just realised that we could remove Protein before dumping to pkl and add it back just after (move line 633 to 568) and then [these changes are not necessary](https://github.com/KosinskiLab/AlphaPulldown/pull/384/commits/e56ccf7a2c165f674d1ebf80ea276efd52a92beb#diff-452d313f6161dfe09a11cf0442ab7d57165cef7ae1e71a23c0b1f6a878890cc7R626-R632)

**Comment by dingquanyu** [comment]
> > I needed to add an extra line of updating the dictionary in the post process, otherwise it crashed later on. but this will not cause the error in the analysis pipeline as the the result pickles were already written out before reaching here.
> 
> Good point. I've also just realised that we could remove Protein before dumping to pkl and add it back just after (move line 633 to 568) and then [these changes are not necessary](https://github.com/KosinskiLab/AlphaPulldown/pull/384/commits/e56ccf7a2c165f674d1ebf80ea276efd52a92beb#diff-452d313f6161dfe09a11cf0442ab7d57165cef7ae1e71a23c0b1f6a878890cc7R626-R632)

I pushed another commit. Is this what you mean?

**Comment by DimaMolod** [comment]
> I pushed another commit. Is this what you mean?
Yep, almost. I also simplified the logic for relaxation the way it was before.

**Comment by dingquanyu** [comment]
> > I pushed another commit. Is this what you mean?
> 
> Yep, almost. I also simplified the logic for relaxation the way it was before.

great! I tested this commit and it avoided the crashes. Now the result pickles can be read by conda env withthout any dependencies installed. It's safe to merge I believe

**Review by dingquanyu — APPROVED** [review]

**Pull request merged**
