### PR TITLE
Fix for custom job creation

### PR DESCRIPTION
**Pull request by dennissv**
Hi, this is a small bug fix in the job creation where only the last job will be ran when using custom job. Currently the multimers object is overwritten for each iteration of the job creation loop causing the bug.

### CODE REVIEW

**Comment by henrywotton** [comment]
Hi @dennissv thanks a lot for the modification! Would you mind sending us your error log? Sorry I didn't get the problem.

**Comment by dennissv** [comment]
Hi @henrywotton Happy to help if I can! There's no error, but at least for me if I create a custom instruction file like custom_mode.txt in example #2;

`O09705;O73557`
`O09705,290-1398;O73557`

It only runs the last job, in this case `O09705,290-1398;O73557`, skipping all the other ones. With this slight modification it avoids overwriting `multimers` when creating the list of multimers in `create_custom_jobs` resulting in all jobs being run.

**Comment by henrywotton** [comment]
> Hi @henrywotton Happy to help if I can! There's no error, but at least for me if I create a custom instruction file like custom_mode.txt in example 2;
> 
> `O09705;O73557` `O09705,290-1398;O73557`
> 
> It only runs the last job, in this case `O09705,290-1398;O73557`, skipping all the other ones. With this slight modification it avoids overwriting `multimers` when creating the list of multimers in `create_custom_jobs` resulting in all jobs being run.

I see. Did you specify a ```--job_index``` when trying the example input file?

**Comment by dennissv** [comment]
No, I did not use the `--job_index` parameter.

**Comment by henrywotton** [comment]
Ah I see. ```run_multimer_jobs.py``` is designed to take ```job_index``` and I haven't considered the case where this parameter is not specified so it was written in such way. Thanks for your input again and I will take a look.

**Review by henrywotton — APPROVED** [review]

**Comment by henrywotton** [comment]
Hi @dennissv  Thanks a lot for your contribution. now merged

**Pull request merged**
