### PR TITLE
Reorganise structure of the package

### PR DESCRIPTION
**Pull request by dingquanyu**

### CODE REVIEW

**Comment by DimaMolod** [comment]
example_data in root is data used in manuals, right? so I suggest it better goes to manuals/example_data

**Comment by DimaMolod** [comment]
we can delete conda dir in the root since it's outdated already

**Comment by DimaMolod** [comment]
I suggest we make a simple hierarchy in the `scripts/` folder:
keep `create_individual_features.py` and `run_multimer_jobs.py` in root as the main AP scripts and put the rest (optional) scripts to `alphapulldown/scripts/tools`

**Comment by dingquanyu** [comment]
> we can delete conda dir in the root since it's outdated already

Oh yea good point didn't notice this.

**Comment by dingquanyu** [comment]
> example_data in root is data used in manuals, right? so I suggest it better goes to manuals/example_data

Well spotted.

**Comment by dingquanyu** [comment]
> I suggest we make a simple hierarchy in the `scripts/` folder: keep `create_individual_features.py`, `run_multimer_jobs.py` and `run_structure_prediction.py` in root as the main AP scripts and put the rest (optional) scripts to `alphapulldown/scripts/tools` as i understand `run_structure_prediction.py` will eventually engulf `run_multimeric_jobs.py`?

Yep that's right. run_structure_prediction will replace run_multimer_jobs.py I'm not sure whether a tools/ within scripts is needed. What do you think ? @jkosinski @maurerv

**Comment by DimaMolod** [comment]
and a few minor comments:
1) https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/objects.py#L24-L30 should go to file_handlings.py
2) https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L196-L223 probably as well to file_handlings.py
3) https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L225-L236 plotting.py
4) https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L196-L223 file_handlings.py

**Comment by maurerv** [comment]
@dingquanyu run_multimer_jobs.py should best be kept for backwards compatibility. Internally, I will modify it to use the new run_structure_prediction.py

**Comment by DimaMolod** [comment]
maybe also move [stereo_chemical_props.txt](https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/stereo_chemical_props.txt) from root to a new dir `common/`

**Comment by dingquanyu** [comment]
> and a few minor comments:
> 
>     1. https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/objects.py#L24-L30 should go to file_handlings.py
> 
>     2. https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L196-L223 probably as well to file_handlings.py
> 
>     3. https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L225-L236 plotting.py
> 
>     4. https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/alphapulldown/utils/save_meta_data.py#L238-L263 file_handlings.py

1. fixed in [167e7f3](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/167e7f35f9c2fd7027cb07ef1df1e5536c791337) 
2. fixed in [58541e5](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/58541e581ad34f3ee2a364e9cb851774e7ba9e0c)
3. fixed in [f8d5ff1](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/f8d5ff1e8ce5e99f89330fc9120abc326ab003ed)
4. fixed in [c97ece3](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/c97ece3d3d7be052c684464fa5ff88b8f1fa33cf) @DimaMolod

**Comment by dingquanyu** [comment]
> @dingquanyu run_multimer_jobs.py should best be kept for backwards compatibility. Internally, I will modify it to use the new run_structure_prediction.py

OK thanks for taking care of this. reorganise branch won't touch any of these 2 files as well.

**Comment by dingquanyu** [comment]
> maybe also move [stereo_chemical_props.txt](https://github.com/KosinskiLab/AlphaPulldown/blob/reorganise/stereo_chemical_props.txt) from root to a new dir `common/`

Good suggestion. I've moved it to a dir called package_data: [5e2c7fd](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/5e2c7fdd2101000d54edbbd64814a01737311999)

**Review by DimaMolod — APPROVED** [review]
looks AWESOME

**Review by maurerv — APPROVED** [review]

**Comment by dingquanyu** [comment]
@DimaMolod could you double check [7e035f2](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/7e035f2a733ab90af71684b7aac8aa1e184e4753) and [5bb4491](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/5bb4491775ddb9383014e574d532dd4799c9ef89) ? Thanks :-D

**Comment by DimaMolod** [comment]
> @DimaMolod could you double check [7e035f2](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/7e035f2a733ab90af71684b7aac8aa1e184e4753) and [5bb4491](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/5bb4491775ddb9383014e574d532dd4799c9ef89) ? Thanks :-D

Sure :-) I think no need to import it explicitly in [check_predict_structure.py](https://github.com/KosinskiLab/AlphaPulldown/pull/285/commits/5bb4491775ddb9383014e574d532dd4799c9ef89) since we import predict_structure.py few lines below, right? so all dependencies are already there

**Pull request merged**
