### PR TITLE
Update libffi version

### PR DESCRIPTION
**Pull request by dingquanyu**
Fixed the libffi error when build and push alphapulldown docker image

### CODE REVIEW

**Comment by dingquanyu** [comment]
The GitHub action for building the docker image works fine now but the other GitHub action failed because the disk space is not enough. I think we can merge this for now and I'm working on the update of backend to avoid installing PyTorch and unicode dependencies in the first place.

**Comment by maurerv** [comment]
I have seen other projects get around this problem by reducing the size of the build environment and added that in [4f4f1ef](https://github.com/KosinskiLab/AlphaPulldown/pull/364/commits/4f4f1ef8cf67302e874242f207b6cb6001c53484)

**Review by maurerv — APPROVED** [review]

**Comment by maurerv** [comment]
It appears that moving to the classic conda solver, together with cleaning the build environment, does the trick. However, the classic solver is much slower than libmamba and we should revisit this in the future

**Comment by dingquanyu** [comment]
> It appears that moving to the classic conda solver, together with cleaning the build environment, does the trick. However, the classic solver is much slower than libmamba and we should revisit this in the future.
> 
> @dingquanyu feel free to merge for now

I see. Thanks for working on this issue. I will merge for now.

**Pull request merged**
