### PR TITLE
Backend revision

### PR DESCRIPTION
**Pull request by dingquanyu**

### CODE REVIEW

**Comment by dingquanyu** [comment]
@DimaMolod Currently postprocessing failed here if template sequence is not identical to the query sequence e.g. when template is shorter than the query, it will pad template sequence and template_aatype will contain "-" residue, which causes error when creating protein object. You could just use template mmcif file directly when calculating RMSD. https://github.com/KosinskiLab/AlphaPulldown/blob/03cd0f42428ec4858194326bd95d99878180dee9/alphapulldown/folding_backend/alphafold_backend.py#L562

**Comment by DimaMolod** [comment]
I think you cannot use the mmcif directly if we use my TrueMultimer mode and not Geoffrey's mode

**Comment by DimaMolod** [comment]
https://github.com/KosinskiLab/AlphaPulldown/blob/backend_revision/alphapulldown/folding_backend/alphafold_backend.py#L303-L310
can be changed to 
```
num_models = len(model_runners)
for model_index, (model_name, model_runner) in enumerate(model_runners.items()):
    if model_index < START:
        continue
    t_0 = time.time()
    ...
```

**Comment by DimaMolod** [comment]
https://github.com/KosinskiLab/AlphaPulldown/blob/backend_revision/alphapulldown/scripts/run_structure_prediction.py#L318
should be
`flags_dict["msa_depth_scan"] = args.msa_depth_scan`
Does it work?

**Comment by dingquanyu** [comment]
> https://github.com/KosinskiLab/AlphaPulldown/blob/backend_revision/alphapulldown/folding_backend/alphafold_backend.py#L303-L310 can be changed to
> 
> ```
> num_models = len(model_runners)
> for model_index, (model_name, model_runner) in enumerate(model_runners.items()):
>     if model_index < START:
>         continue
>     t_0 = time.time()
>     ...
> ```

Good catch. I've removed the redundant part

**Comment by dingquanyu** [comment]
> https://github.com/KosinskiLab/AlphaPulldown/blob/backend_revision/alphapulldown/scripts/run_structure_prediction.py#L318 should be `flags_dict["msa_depth_scan"] = args.msa_depth_scan` Does it work?

Good catch. I have renamed it and renamed the gradient_msa_depth flag from the refactor.py to msa_depth_scan

**Pull request merged**
