### PR TITLE
Dima small patches

### LINKED ISSUE #16: Could we have an option for run_multimer_jobs.py to just print the number of all jobs?
Just to get the total number for slurm array script

### PR DESCRIPTION
**Pull request by DimaMolod**
Fixes #16 and #103 
reports AP version both when creating features and running predictions
clean imports and use various logging levels
reports if the run was successful

### CODE REVIEW

**Comment by dingquanyu** [comment]
Test: added a comment

**Comment by DimaMolod** [comment]
Please have a look at alphafold_backend.py structure - what do you think about moving ranking, relaxation, resuming, saving jsons and plots to postprocessing and keep only the prediction (and maybe saving original unrelaxed pdbs) in predict?

**Comment by dingquanyu** [comment]
@DimaMolod line 285 should be indented within the if skip_template:block otherwise it will set it to 0 when templates should be use: https://github.com/KosinskiLab/AlphaPulldown/blob/f5416c77d698f8a654e6b4a70a87e8a491bc2ff7/alphapulldown/folding_backend/alphafold_backend.py#L285

**Comment by dingquanyu** [comment]
@DimaMolod Could you not make num_template to 0 as in multimer inference, num_template will be a denominator here: https://github.com/google-deepmind/alphafold/blob/032e2f26732d1473ec5db7ff5b8572754576e459/alphafold/model/modules_multimer.py#L889

**Comment by dingquanyu** [comment]
@DimaMolod Could you add this set_verbosity back here: https://github.com/KosinskiLab/AlphaPulldown/blob/f5416c77d698f8a654e6b4a70a87e8a491bc2ff7/alphapulldown/objects.py#L8 Deep mind sets the verbose in their codes

**Comment by dingquanyu** [comment]
@DimaMolod isn't it gonna crash here if skip_templates and multimeric_mode are both True: 
https://github.com/KosinskiLab/AlphaPulldown/blob/f5416c77d698f8a654e6b4a70a87e8a491bc2ff7/alphapulldown/folding_backend/alphafold_backend.py#L290

**Comment by DimaMolod** [comment]
thanks @dingquanyu I fixed --skip_templates issues using colabfold function, as we agreed in slack
661269323e3db9732e31862d0b0c40b0ec43d85d and 72222c0c802fdd1d498a28a4e83372874bf1d4d1
I don't see the point in returning default logging level (info) to objects.py as we won't be able to use debug mode there at all.
AlphaFold probably had their own reasons?..

**Pull request merged**
