### PR TITLE
Fix 362

### PR DESCRIPTION
**Pull request by dingquanyu**
1. change "model_names" to "DEFINE_list"
2. make AlphaPulldown compatible with old versions of AlphaFold Multimer

### CODE REVIEW

**Comment by dingquanyu** [comment]
Hold on somehow my AlphaFold_backend.py does not have the new commits from the previous merge

**Comment by DimaMolod** [comment]
exactly, there seems to be no convert_to_modelcif flag for run_prediction and the corresponding execution part in the postprocessing anymore...

**Comment by dingquanyu** [comment]
> exactly, there seems to be no convert_to_modelcif flag for run_prediction and the corresponding execution part in the postprocessing is missing...also the resume fix we did on Mondaz

yea that's so weird, especially because I branched out only after pulling the latest main branch. I think now it's fine. Running the tests right now

**Comment by dingquanyu** [comment]
> exactly, there seems to be no convert_to_modelcif flag for run_prediction and the corresponding execution part in the postprocessing is missing...also the resume fix we did on Mondaz

Yep the tests are finished. I believe it's safe to merge

**Review by DimaMolod — APPROVED** [review]
you tested all three possibilities, right? 
1) model_names_custom = <new models> 
2) model_names_custom= <old_models> 
3) model_names_custom = None

**Comment by dingquanyu** [comment]
> you tested all three possibilities, right?
> 
> 1. model_names_custom = <new_models>
> 2. model_names_custom= <old_models>
> 3. model_names_custom = None

Yea that's right

**Pull request merged**
