### PR TITLE
Add interface PAE and plddt calculation to anlaysis pipeline

### PR DESCRIPTION
**Pull request by dingquanyu**
Need to add biopandas as a dependency to config

### CODE REVIEW

**Comment by dingquanyu** [comment]
@DimaMolod In this PR I changed AlphaFold backend so that it writes iptm scores in the ranking_debug.json as well. By doing so, the analysis pipeline can avoid reading the result pickles. I think after this, we are save to remove the result pickles compleletly in the post-prediction process, as now pae, iptm are all written in the jsons. What do you think of this?

**Comment by DimaMolod** [comment]
> @DimaMolod In this PR I changed AlphaFold backend so that it writes iptm scores in the ranking_debug.json as well. By doing so, the analysis pipeline can avoid reading the result pickles. I think after this, we are save to remove the result pickles compleletly in the post-prediction process, as now pae, iptm are all written in the jsons. What do you think of this?

@dingquanyu I think generally it's a good idea. I haven't seen the code yet, though. We need to make sure it works for monomers, where there are no iptm scores. The ranking uses different confidence scores for monomers and multimers. @jkosinski do you think there is smth else we need from the pickles for default runs?
Also convert_to_modelcif will die without pickles, need to keep the proper order in postprocessing (and eventually modify the converter).

**Comment by dingquanyu** [comment]
> > @DimaMolod In this PR I changed AlphaFold backend so that it writes iptm scores in the ranking_debug.json as well. By doing so, the analysis pipeline can avoid reading the result pickles. I think after this, we are save to remove the result pickles compleletly in the post-prediction process, as now pae, iptm are all written in the jsons. What do you think of this?
> 
> @dingquanyu I think generally it's a good idea. I haven't seen the code yet, though. We need to make sure it works for monomers, where there are no iptm scores. The ranking uses different confidence scores for monomers and multimers. @jkosinski do you think there is smth else we need from the pickles for default runs? Also convert_to_modelcif will die without pickles, need to keep the proper order in postprocessing (and eventually modify the converter).

@DimaMolod good point on the monomer structure. I have to modify some parts so that it won't crash if itpm does not exist in the results.

**Comment by DimaMolod** [comment]
@dingquanyu also check what happens when we resume predictions. It should amend the json, not rewrite it.

**Pull request merged**
